// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:94b65888-2f4e-4e5b-8222-6bfa84fddc59",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_4y1owtgAu",
    "aws_user_pools_web_client_id": "4t9g248cjmfe9s1ktdbbf5nul0"
};


export default awsmobile;
